apiVersion: v1
kind: Service
metadata:
  name: oo2d
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "oo2d"
    port: 8080
  selector:
    app: oo2d
